version: '3'

services:
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./data:/var/lib/mysql
  pwp:
    image: "wordpress:latest"
    environment:
      WORDPRESS_DB_PASSWORD: 'password'